### ISSUE TITLE
Error if no issues/tasks in the Jira project

### ISSUE THREAD

**Issue by CapnK** [WeConnect/issue-tracker#1]
![no_tasks_error](https://cloud.githubusercontent.com/assets/1552443/11104102/a78de548-88be-11e5-8787-19cbe4eeb968.png)

**Comment by alnjxn** [comment]
@CapnK I loaded issue tracker project with no tasks or issues and did not receive the error. Can you document the steps you took when you received this message?

**Comment by CapnK** [comment]
@alnjxn I think we fixed this back in January on Arup repository, at https://github.com/ArupAus/issue-tracker/commit/182c95e432c023dd1bf6ece106aa4301cdc1b916

That commit was most likely merged into the WeWork repository before it was opened up.
